export const groupedLanguages = {
  Europe: [
    { name: 'Spanish', value: 'es' },
    { name: 'French', value: 'fr' },
    { name: 'German', value: 'de' },
    { name: 'Italian', value: 'it' },
    { name: 'Portuguese', value: 'pt' },
    { name: 'Dutch', value: 'nl' },
    { name: 'Russian', value: 'ru' },
    { name: 'Polish', value: 'pl' },
    { name: 'Ukrainian', value: 'uk' },
    { name: 'Swedish', value: 'sv' },
    { name: 'Danish', value: 'da' },
    { name: 'Finnish', value: 'fi' },
    { name: 'Norwegian', value: 'no' },
    { name: 'Greek', value: 'el' },
    { name: 'Czech', value: 'cs' },
    { name: 'Romanian', value: 'ro' },
    { name: 'Hungarian', value: 'hu' },
  ],
  Asia: [
    { name: 'Chinese (Simplified)', value: 'zh' },
    { name: 'Chinese (Traditional)', value: 'zh-TW' },
    { name: 'Japanese', value: 'ja' },
    { name: 'Korean', value: 'ko' },
    { name: 'Hindi', value: 'hi' },
    { name: 'Arabic', value: 'ar' },
    { name: 'Turkish', value: 'tr' },
    { name: 'Vietnamese', value: 'vi' },
    { name: 'Thai', value: 'th' },
    { name: 'Indonesian', value: 'id' },
    { name: 'Malay', value: 'ms' },
    { name: 'Bengali', value: 'bn' },
    { name: 'Hebrew', value: 'he' },
  ],
  Americas: [
    { name: 'English (US)', value: 'en' },
    { name: 'Spanish (Mexico)', value: 'es-MX' },
    { name: 'Portuguese (Brazil)', value: 'pt-BR' },
    { name: 'French (Canada)', value: 'fr-CA' },
  ],
  Africa: [
    { name: 'Swahili', value: 'sw' },
    { name: 'Amharic', value: 'am' },
    { name: 'Yoruba', value: 'yo' },
    { name: 'Zulu', value: 'zu' },
    { name: 'Afrikaans', value: 'af' },
  ],
  Oceania: [{ name: 'English (Australia)', value: 'en-AU' }],
};
